### ISSUE TITLE
🚨 Exposed API key

### ISSUE THREAD

**Issue by akankov** [ShivanshAr97/CourierHacks#1]
You should not expose secret info in your [code](https://github.com/ShivanshAr97/CourierHacks/blob/main/server/index.js#L4).

**Comment by ShivanshAr97** [comment]
Thanks !
The issue has been solved now 🙌

> You should not expose secret info in your [code](https://github.com/ShivanshAr97/CourierHacks/blob/main/server/index.js#L4).
